---
title: Jumaidil Awal
timezone: Asia/Jakarta
collections:
  categories:
    title: Categories
    output: true
  pages:
    title: Pages
    output: true
  posts:
    title: Posts
    output: true
  tags:
    title: Tags
    output: true
  uploads:
    title: Uploads
    output: true
defaults:
- scope:
    path: ''
    type: posts
  values:
    layout: post
    permalink: "/posts/:title/"
- scope:
    path: ''
    type: pages
  values:
    layout: default
- scope:
    path: ''
    type: tags
  values:
    slug: 
    layout: default
    permalink: "/tag/:slug/"
- scope:
    path: ''
    type: categories
  values:
    slug: 
    layout: default
    permalink: "/category/:slug/"
description: Jumaidil Awal
permalink: pretty
plugins:
- jekyll-remote-theme
- jekyll-favicon
remote_theme: pages-themes/cayman@v0.2.0
author:
  name: Jumaidil Awal
  photo: "/uploads/best-profile-photo-ever.png"
favicon:
  source: "/uploads/best-profile-photo-ever.png"
