---
title: "{{page.author.name}}'s Profile"
timezone: Asia/Jakarta
collections:
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
defaults:
- scope:
    path: ''
    type: posts
  values:
    layout: post
    permalink: "/posts/:title/"
- scope:
    path: ''
    type: pages
  values:
    layout: page
description: |-
  {{page.author.name}}'s Profile
  ![yours truly elegantly sniffing a sakura flower]({{page.author.photo}})
permalink: pretty
plugins:
- jekyll-remote-theme
remote_theme: pages-themes/cayman@v0.2.0
author:
  name: Jumaidil Awal
  photo: "/uploads/best-profile-photo-ever.png"
